import LegalPageHero from '@/components/LegalPageHero'
import LegalContent from '@/components/LegalContent'

export const metadata = {
  title: 'Privacy Policy',
  description: 'Learn how Pulse Business Solutions Inc collects, uses, and protects your data.'
}

export default function PrivacyPolicyPage() {
  const blocks = [
    { type: 'paragraph' as const, content: 'Effective date: August 02, 2025' },
    { type: 'heading' as const, level: 2, content: '1. Introduction' },
    { type: 'paragraph' as const, content: 'Welcome to Pulse Business Solutions Inc.' },
    { type: 'paragraph' as const, content: 'Pulse Business Solutions Inc ("us", "we", or "our") operates https://www.pulsepro.ai and Pulse mobile application (hereinafter referred to as "Service").' },
    { type: 'paragraph' as const, content: 'Our Privacy Policy governs your visit to https://www.pulsepro.ai and Pulse mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Service.' },
    { type: 'paragraph' as const, content: 'We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.' },
    { type: 'paragraph' as const, content: 'Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").' },
    { type: 'heading' as const, level: 2, content: '2. Definitions' },
    { type: 'paragraph' as const, content: 'SERVICE means the https://www.pulsepro.ai website and Pulse mobile application operated by Pulse Business Solutions Inc.' },
    { type: 'paragraph' as const, content: 'PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).' },
    { type: 'paragraph' as const, content: 'USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).' },
    { type: 'paragraph' as const, content: 'COOKIES are small files stored on your device (computer or mobile device).' },
    { type: 'paragraph' as const, content: 'DATA CONTROLLER means a natural or legal person who determines the purposes for which and the manner in which any personal data are processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.' },
    { type: 'paragraph' as const, content: 'DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.' },
    { type: 'paragraph' as const, content: 'DATA SUBJECT is any living individual who is the subject of Personal Data.' },
    { type: 'paragraph' as const, content: 'THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.' },
    { type: 'heading' as const, level: 2, content: '3. Information Collection and Use' },
    { type: 'paragraph' as const, content: 'We collect several different types of information for various purposes to provide and improve our Service to you.' },
    { type: 'heading' as const, level: 2, content: '4. Types of Data Collected' },
    { type: 'heading' as const, level: 3, content: 'Personal Data' },
    { type: 'paragraph' as const, content: 'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:' },
    { type: 'list' as const, items: ['(a) Email address', '(b) First name and last name', '(c) Phone number', '(d) Address, State, Province, ZIP/Postal code, City', '(e) Cookies and Usage Data'] },
    { type: 'paragraph' as const, content: 'We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at hello@pulsepro.ai.' },
    { type: 'heading' as const, level: 3, content: 'Usage Data' },
    { type: 'paragraph' as const, content: 'We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device ("Usage Data").' },
    { type: 'paragraph' as const, content: 'This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.' },
    { type: 'paragraph' as const, content: 'When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.' },
    { type: 'heading' as const, level: 3, content: 'Location Data' },
    { type: 'paragraph' as const, content: 'We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.' },
    { type: 'paragraph' as const, content: 'You can enable or disable location services when you use our Service at any time by way of your device settings.' },
    { type: 'heading' as const, level: 3, content: 'Tracking Cookies Data' },
    { type: 'paragraph' as const, content: 'We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.' },
    { type: 'paragraph' as const, content: 'Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.' },
    { type: 'paragraph' as const, content: 'You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.' },
    { type: 'paragraph' as const, content: 'Examples of Cookies we use:' },
    { type: 'list' as const, items: ['(a) Session Cookies: We use Session Cookies to operate our Service.', '(b) Preference Cookies: We use Preference Cookies to remember your preferences and various settings.', '(c) Security Cookies: We use Security Cookies for security purposes.', '(d) Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.'] },
    { type: 'heading' as const, level: 3, content: 'Other Data' },
    { type: 'paragraph' as const, content: 'While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.' },
    { type: 'heading' as const, level: 2, content: '5. Use of Data' },
    { type: 'paragraph' as const, content: 'Pulse Business Solutions Inc uses the collected data for various purposes:' },
    { type: 'list' as const, items: ['(a) to provide and maintain our Service;', '(b) to notify you about changes to our Service;', '(c) to allow you to participate in interactive features of our Service when you choose to do so;', '(d) to provide customer support;', '(e) to gather analysis or valuable information so that we can improve our Service;', '(f) to monitor the usage of our Service;', '(g) to detect, prevent and address technical issues;', '(h) to fulfill any other purpose for which you provide it;', '(i) to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;', '(j) to provide you with notices about your account and/or subscription;', '(k) to provide you with news, special offers and general information unless you have opted not to receive such information;', '(l) in any other way we may describe when you provide the information;', '(m) for any other purpose with your consent.'] },
    { type: 'heading' as const, level: 2, content: '6. Retention of Data' },
    { type: 'paragraph' as const, content: 'We will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to comply with legal obligations, resolve disputes, and enforce agreements.' },
    { type: 'paragraph' as const, content: 'Usage Data is generally retained for a shorter period, except when used to strengthen security or improve functionality, or when legally required.' },
    { type: 'heading' as const, level: 2, content: '7. Transfer of Data' },
    { type: 'paragraph' as const, content: 'Your information, including Personal Data, may be transferred to computers located outside your jurisdiction where data protection laws may differ.' },
    { type: 'paragraph' as const, content: 'If you are located outside the United States and choose to provide information to us, note that we transfer the data, including Personal Data, to the United States and process it there.' },
    { type: 'paragraph' as const, content: 'Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.' },
    { type: 'paragraph' as const, content: 'We take reasonable steps to ensure your data is treated securely and in accordance with this Privacy Policy.' },
    { type: 'heading' as const, level: 2, content: '8. Disclosure of Data' },
    { type: 'paragraph' as const, content: 'We may disclose personal information that we collect or you provide:' },
    { type: 'list' as const, items: ['(a) For law enforcement if required by law.', '(b) In business transactions such as mergers or acquisitions.', '(c) To subsidiaries and affiliates.', '(d) To contractors and service providers.', '(e) To fulfill the purpose for which you provide it.', '(f) To include your company’s logo on our website.', '(g) With your consent.', '(h) If necessary to protect rights, property, or safety.'] },
    { type: 'heading' as const, level: 2, content: '9. Security of Data' },
    { type: 'paragraph' as const, content: 'No method of transmission over the Internet or electronic storage is 100% secure. We strive to use commercially acceptable means to protect your Personal Data but cannot guarantee absolute security.' },
    { type: 'heading' as const, level: 2, content: '10. GDPR Rights' },
    { type: 'paragraph' as const, content: 'If you are a resident of the EU/EEA you have certain rights under GDPR.' },
    { type: 'list' as const, items: ['(a) Right to access/update/delete information.', '(b) Right of rectification.', '(c) Right to object.', '(d) Right of restriction.', '(e) Right to data portability.', '(f) Right to withdraw consent.'] },
    { type: 'paragraph' as const, content: 'You may be asked to verify your identity before we respond. You have the right to complain to a Data Protection Authority.' },
    { type: 'heading' as const, level: 2, content: '11. CalOPPA Rights' },
    { type: 'paragraph' as const, content: 'California law requires posting a privacy policy describing information practices.' },
    { type: 'list' as const, items: ['(a) Users can visit anonymously.', '(b) Privacy Policy link includes the word “Privacy”.', '(c) Users notified of changes on this page.', '(d) Users can change personal information via hello@pulsepro.ai.'] },
    { type: 'paragraph' as const, content: 'We honor Do Not Track signals.' },
    { type: 'heading' as const, level: 2, content: '12. CCPA Rights' },
    { type: 'paragraph' as const, content: 'California residents can request disclosure, deletion, and opt out of sale of data.' },
    { type: 'list' as const, items: ['(a) What personal information we have collected.', '(b) Delete your personal information.', '(c) Stop selling your personal information (we do not sell).'] },
    { type: 'paragraph' as const, content: 'Requests: hello@pulsepro.ai.' },
    { type: 'heading' as const, level: 2, content: '13. Service Providers' },
    { type: 'paragraph' as const, content: 'We may employ third parties to facilitate Service.' },
    { type: 'heading' as const, level: 2, content: '14. Analytics' },
    { type: 'paragraph' as const, content: 'We may use analytics providers like Google Analytics, Firebase, Cloudflare.' },
    { type: 'heading' as const, level: 2, content: '15. CI/CD Tools' },
    { type: 'paragraph' as const, content: 'We may use GitHub, GitLab CI/CD, CircleCI.' },
    { type: 'heading' as const, level: 2, content: '16. Advertising' },
    { type: 'paragraph' as const, content: 'We may use Google AdSense DoubleClick.' },
    { type: 'heading' as const, level: 2, content: '17. Behavioral Remarketing' },
    { type: 'paragraph' as const, content: 'We use remarketing services (Google Ads, Facebook).' },
    { type: 'heading' as const, level: 2, content: '18. Payments' },
    { type: 'paragraph' as const, content: 'We use third-party payment processors (PayPal/Braintree, Apple, Google Play). We do not store card details.' },
    { type: 'heading' as const, level: 2, content: '19. Links to Other Sites' },
    { type: 'paragraph' as const, content: 'Our Service may contain links to third-party sites. Review their Privacy Policies.' },
    { type: 'heading' as const, level: 2, content: '20. Children’s Privacy' },
    { type: 'paragraph' as const, content: 'We do not knowingly collect data from children under 18.' },
    { type: 'heading' as const, level: 2, content: '21. Changes to This Privacy Policy' },
    { type: 'paragraph' as const, content: 'We may update this Privacy Policy periodically. Changes are effective when posted.' },
    { type: 'heading' as const, level: 2, content: '22. Contact Us' },
    { type: 'paragraph' as const, content: 'Questions: hello@pulsepro.ai.' }
  ] satisfies any[]

  return (
    <main className='bg-[#FDF6E9] min-h-screen'>
      <LegalPageHero
        title='Privacy Policy'
        subtitle='Your privacy is important to us. Learn how we collect, use, and protect your information.'
        effectiveDate='August 02, 2025'
      />
      <LegalContent blocks={blocks} />
    </main>
  )
}
